- name: Deploy Redmine
  hosts: webservers
  become: true
  tasks:
    - name: Установить Docker
      apt:
        name: docker.io
        state: present

    - name: Запустить Redmine
      docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        ports:
          - "80:3000"
        env:
          REDMINE_DB_MYSQL: "db"
          REDMINE_DB_PASSWORD: "example"
          REDMINE_SECRET_KEY_BASE: "supersecretkey"
