- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker Compose is installed
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create Redmine directory
  file:
    path: /opt/redmine
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: files/docker-compose.yml
    dest: /opt/redmine/docker-compose.yml

- name: Copy .env file
  template:
    src: templates/.env.j2
    dest: /opt/redmine/.env

- name: Start Redmine
  command: docker-compose up -d
  args:
    chdir: /opt/redmine