redmine_db_password: "{{ vault_redmine_db_password }}"
redmine_secret_key_base: "{{ vault_redmine_secret_key_base }}"
mysql_root_password: "{{ vault_mysql_root_password }}"
datadog_api_key: "{{ vault_datadog_api_key }}"